### PR TITLE
ghw: switch to fork

### PR DESCRIPTION
**Pull request by fromanirh**
we need few more unmerged changes to ghw, so we temporarily
switch to our fork until the changes are merged u/s.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/cc @cynepco3hahue @yanirq 
FYI @MarSik @marcel-apf

**Comment by fromanirh** [comment]
do we prefer to change the import or to workaround the issue at the application level (we can do it), leaving the import alone?

**Comment by yanirq** [comment]
> do we prefer to change the import or to workaround the issue at the application level (we can do it), leaving the import alone?

Depends how many times we will need to change it and keep track at the application level. Personally I don't have a strong opinion here about either.
This looks good to me in case we go with the imports.

**Comment by fromanirh** [comment]
> > do we prefer to change the import or to workaround the issue at the application level (we can do it), leaving the import alone?
> 
> Depends how many times we will need to change it and keep track at the application level. Personally I don't have a strong opinion here about either.
> This looks good to me in case we go with the imports.

me neither. What works best for the team. Worth noting that once u/s catches up, we will need to update go.{mod,sum} anyway to consume the changes.

**Comment by cynepco3hahue** [comment]
I prefer to have the replace directive
/lgtm
/hold give others chance to review

**Comment by fromanirh** [comment]
no longer needed

**Pull request closed without merging**
