### PR TITLE
Temporarily disable RT kernel

### PR DESCRIPTION
**Pull request by slintes**
Reason: https://bugzilla.redhat.com/show_bug.cgi?id=1811630

### CODE REVIEW

**Comment by simon3z** [comment]
@slintes @MarSik what are the other options (if any) that we dismissed to address this temporary issue?

**Comment by MarSik** [comment]
> @slintes @MarSik what are the other options (if any) that we dismissed to address this temporary issue?

This is master branch only. 4.4 seems to be fine. There seems to be no workaround since the packages are simply missing afaik.

**Comment by slintes** [comment]
> > @slintes @MarSik what are the other options (if any) that we dismissed to address this temporary issue?
> 
> This is master branch only. 4.4 seems to be fine. There seems to be no workaround since the packages are simply missing afaik.

Correct. No way to install rt kernel on OCP 4.5 atm, and OCP 4.4 is fine.
Because of the failed installation of the rt kernel the Node is getting degraded, MCP update never finishes, and CI fails before our tests run. With this patch we will still see a test failure, but at least tests will run.

**Comment by yanirq** [comment]
/lgtm
/hold
@slintes  feel free to remove hold once you see fit.   only the RT test is failing as expected

**Comment by slintes** [comment]
Only expected `[It] should have RT kernel enabled ` test failure

**Comment by slintes** [comment]
> /lgtm
> /hold
> @slintes feel free to remove hold once you see fit. only the RT test is failing as expected

ha, didn't see this, thx

/hold cancel

**Pull request merged**
