### PR TITLE
Update go version to 1.17.2

### PR DESCRIPTION
**Pull request by marioferh**
Update go version to 1.17.2

### CODE REVIEW

**Comment by fromanirh** [comment]
I'm not sure if we require changes to `openshift/release` or not

**Comment by cynepco3hahue** [comment]
> I'm not sure if we require changes to `openshift/release` or not

nope, it should use our tools image to build binaries.

**Comment by cynepco3hahue** [comment]
Know I remember that the updated Dockerfiles is used only after the merged, so the PR is using the old one.

**Comment by fromanirh** [comment]
> Know I remember that the updated Dockerfiles is used only after the merged, so the PR is using the old one.

yes. Prow use the content of the branch HEAD to run.

**Comment by cynepco3hahue** [comment]
/lgtm
/approve
and wait for following PR to update deps and generated files.

**Comment by cynepco3hahue** [comment]
Only CPU load balancing test is failing.
/override ci/prow/e2e-gcp
/override ci/prow/e2e-gcp-operator-upgrade

**Pull request merged**
