### PR TITLE
Add ethtool -k and ethtool -l to must gather collected data

### PR DESCRIPTION
**Pull request by marioferh**
Add ethtool -k and ethtool -l to must gather collected data
Save in ethtool_features and ethtool_channels files

Signed-off-by: Mario Fernandez <mariofer@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
do we have a test for that ? or what is tested in a different method ?

**Comment by marioferh** [comment]
> do we have a test for that ? or what is tested in a different method ?

the tests are in NTO: https://github.com/openshift/cluster-node-tuning-operator/pull/365/files

But it is needed to upload new data. I want to do a new test with real data generated in the cluster, when that PR will be merged I will add the test for these files also.

**Comment by marioferh** [comment]
After this one we can add test in NTO
https://github.com/openshift/cluster-node-tuning-operator/pull/442

**Comment by marioferh** [comment]
Test in: https://github.com/openshift/cluster-node-tuning-operator/pull/450

**Pull request merged**
