### PR TITLE
Add nil check before creating preboot ignition

### PR DESCRIPTION
**Pull request by yanirq**
**What is the Probelm?**
When cpu.reserved field is missing in perfomance profile, a nil panic will occur:
`bserved a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)`

**What was fixed**
Added a nil check before creating ignition content for pre boot tuning that relies on cpu.reserved value

**Note**
Another way to ensure proper behaviour here is to validate that the field exists if its defined as a mandatory field

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@yanirq Please unhold once the CI passed.

**Comment by slintes** [comment]
Fixes #92 

/cherrypick release-4.4

**Pull request merged**
