### PR TITLE
[release-4.4] Updating qe-tools to v0.1.6

### PR DESCRIPTION
**Pull request by dshchedr**
This is a cherry-pick of #167

### CODE REVIEW

**Comment by slintes** [comment]
ah sorry, this can't work. I need to cherry pick a CI fix first...

**Comment by slintes** [comment]
https://github.com/openshift-kni/performance-addon-operators/pull/171

**Comment by dshchedr** [comment]
> ah sorry, this can't work. I need to cherry pick a CI fix first...
ah, right, thanks!

**Pull request merged**
