### PR TITLE
[release-4.5] Update default tag

### PR DESCRIPTION
**Pull request by slintes**
Signed-off-by: Marc Sluiter <msluiter@redhat.com>

### CODE REVIEW

**Comment by dshchedr** [comment]
should we update update image tag in 4.4.0 CSV?

https://github.com/openshift-kni/performance-addon-operators/blob/8244d492d4222fe0c426a286320034aa4ada23ed/deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml#L47

https://github.com/openshift-kni/performance-addon-operators/blob/8244d492d4222fe0c426a286320034aa4ada23ed/deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml#L129

**Comment by slintes** [comment]
> should we update update image tag in 4.4.0 CSV?
> 
> https://github.com/openshift-kni/performance-addon-operators/blob/8244d492d4222fe0c426a286320034aa4ada23ed/deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml#L47
> 
> https://github.com/openshift-kni/performance-addon-operators/blob/8244d492d4222fe0c426a286320034aa4ada23ed/deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml#L129

I'd say let's keep the release tag for 4.4

**Pull request merged**
