### PR TITLE
[release-4.6] Provide dockerfile to generate index.db via opm

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
/hold
wait for merge of https://github.com/openshift/release/pull/13225

**Comment by fromanirh** [comment]
> @cynepco3hahue: No Bugzilla bug is referenced in the title of this pull request.
> To reference a bug, add 'Bug XXX:' to the title of this pull request and request another bug refresh with `/bugzilla refresh`.

waived because this change doens't affect production code, but rather how we integrate with u/s CI

**Pull request merged**
