### PR TITLE
Bug 1903820: watch machine config pools not owned by the performance profile

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Our logic to watch for machine config pools icorrect, because
the machine config pools not owned by the performance profile.

To fix it our logic will watch all machine config pools and will map
it to the performance profile.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
will this cover the case of exiting profile ?  (e.g. discovery mode)

**Comment by cynepco3hahue** [comment]
> will this cover the case of exiting profile ? (e.g. discovery mode)

Sure, why not :)

**Pull request merged**
