### PR TITLE
Improvement for operator upgrade test:

### PR DESCRIPTION
**Pull request by dshchedr**
- it runs all other tests after upgrade
- option to run on a cluster with pre-installed profile
- option to run it on d/s

### CODE REVIEW

**Comment by dshchedr** [comment]
hm, need to update code a little bit

/hold

**Comment by cynepco3hahue** [comment]
/lgtm

@dshchedr Do you have intention to add additional checks under the upgrade test, I know you encounter some but with the change of tuned profile, I prefer to catch such bugs with the CI.

**Comment by dshchedr** [comment]
> @dshchedr Do you have intention to add additional checks under the upgrade test, I know you encounter some but with the change of tuned profile, I prefer to catch such bugs with the CI.

@cynepco3hahue  hm, with this PR we will run all tests  **after** upgrading PAO, so if we have test in _functests/_ folder that covers some specific feature in new version - it should be verified.. 

Do you know some uncovered scenario?

**Comment by dshchedr** [comment]
didn't make changes since previous lgtm, so will add it again :)

/lgtm

**Pull request merged**
