### PR TITLE
Do not update the feature gate anymore

### PR DESCRIPTION
**Pull request by cynepco3hahue**
The topology manager was promoted to beta under the k8s 1.18,
so we do not need to update the default feature gate resource to
enable LatencySensitive feature set.

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@fromanirh @MarSik Please review

**Comment by MarSik** [comment]
@cynepco3hahue Can you explain what will happen on upgrades? Will the feature gate just stay enabled, but cause no issues?

**Comment by cynepco3hahue** [comment]
yes, it the expectation, so we will have two flows

1. clear installation, we will not touch feature gate resource at all
2. update, we will stop to monitor feature gate object

**Pull request merged**
