### PR TITLE
k8s: dump deps to 1.20.4 from 1.18.3

### PR DESCRIPTION
**Pull request by fromanirh**
Trivial bump + trivial fix in the API package pulled by the update.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
yuck: ```pods/openshift-operator-lifecycle-manager_packageserver-86bbbb67f-ng469_packageserver.log.gz:E0315 13:35:03.707911       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference```

**Comment by cynepco3hahue** [comment]
> yuck: `pods/openshift-operator-lifecycle-manager_packageserver-86bbbb67f-ng469_packageserver.log.gz:E0315 13:35:03.707911 1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference`

Hm where do you see it, why the CI passed?

**Comment by fromanirh** [comment]
> > yuck: `pods/openshift-operator-lifecycle-manager_packageserver-86bbbb67f-ng469_packageserver.log.gz:E0315 13:35:03.707911 1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference`
> 
> Hm where do you see it, why the CI passed?

It was in the ci-operator-upgrade lane: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-kni_performance-addon-operators/578/pull-ci-openshift-kni-performance-addon-operators-master-e2e-gcp-operator-upgrade/1371443821304352768

and actually a test failed?! how come CI merged my change?
I don't think my change caused the panic, but still...

**Pull request merged**
