### PR TITLE
Move Performance Profile to V2 API

### PR DESCRIPTION
**Pull request by marcel-apf**
v5:
 - Rebased on master
 - Update the 4.7 CSV and CRD instead of 4.6 (@cynepco3hahue )

v4:
 - Rebased again on master after a e2e test update
 - Fix a minor bug in the e2e test following the rebase

v3:
 - Rebased on master
 - Fixed all v2 issues exposed by the "Webhook Conversion" PR

v2:
 - Rebased on  "webhook conversion PR"
 - Fixed the E2E API versioning test

Add v2 API for the Performance Profile that is identical to v1 and v1apha1 as a first step.
The real gain will be the next PR that will deal with the real issues in hand will be much easier
to review.

Steps:
Generate the new v2 API and add the generated and  webhook conversion code.
Point the code to the new v2 API (the controller and tests will work only with v2 API)
Point the docs and the cluster-setup code to the new API
Add an E2E test for v1 <-> v2 conversion and make the necessary for the v1 <-> v1alpha1  test.

### CODE REVIEW

**Review by fromanirh — APPROVED** [review]
/lgtm
/hold
good enough to move forward
holding to let other reviewers chime in

**Comment by marcel-apf** [comment]
/unhold
Removing the hold since no lgtm yet

**Comment by cynepco3hahue** [comment]
/lgtm

@fromanirh Feel free to unhold once you will review it.

**Comment by fromanirh** [comment]
I think we should stop doing blind retests:
```
msg=failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Quota Check": error(MissingQuota): iam.googleapis.com/quota/service-account-count is not available in global because The required number of resources (5) is more than remaining quota of 0
error: failed to execute wrapped command: exit status 1 
```

**Review by fromanirh — COMMENTED** [review]
/lgtm

**Comment by fromanirh** [comment]
/hold cancel
let's merge as soon as CI allows

**Comment by cynepco3hahue** [comment]
@marcel-apf Please create the following PR under the cnf-features-deploy, to update the vendor and to use API v2.

**Comment by marcel-apf** [comment]
On Tue, Oct 27, 2020, 7:21 AM Artyom Lukianov <notifications@github.com>
wrote:

> @marcel-apf <https://github.com/marcel-apf> Please create the following
> PR under the cnf-features-deploy, to update the vendor and to use API v2.
>


Sure, do you have a similar PR so I can see how is done? I don't think we
have vendor anything for v2, but I'll double check.

Thanks!

**Comment by fromanirh** [comment]
> On Tue, Oct 27, 2020, 7:21 AM Artyom Lukianov ***@***.***> wrote: @marcel-apf <https://github.com/marcel-apf> Please create the following PR under the cnf-features-deploy, to update the vendor and to use API v2.
> Sure, do you have a similar PR so I can see how is done? I don't think we have vendor anything for v2, but I'll double check. Thanks! —

You can start from https://github.com/openshift-kni/cnf-features-deploy/pull/343

**Pull request merged**
