### PR TITLE
Remove worker-rt MCP with deploy clean-up

### PR DESCRIPTION
**Pull request by gsr-shanks**
Remove worker-rt MCP while performing 'make cluster-clean'

### CODE REVIEW

**Comment by slintes** [comment]
hm, exit code 56 probably is curl (failure in receiving network data) with a temporary error. Let's try again....

/retest

**Comment by slintes** [comment]
hm, works locally and on other PRs. The change can't cause the problem. Let's retry later...

**Comment by slintes** [comment]
@gsr-shanks sorry, you need to rebase

**Comment by gsr-shanks** [comment]
Looks like I missed something.

**Pull request closed without merging**
