### PR TITLE
prepare for branch 4.8.0

### PR DESCRIPTION
**Pull request by fromanirh**
A bunch of updates to version numbers and new files (when relevant),
cloned from the 4.7.0 counterparts.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
resource exhaustion again

**Comment by cynepco3hahue** [comment]
Hm I remember I already saw such an error in the past:
```
 Expected
      
      <string>: registry.build02.ci.openshift.org/ci-op-2f4zdf4y/pipeline@sha256:f21d674b4027fefea63d6179870262ae2625ae96d220bd4b6f62a43ff70ffd67
  not to equal
      <string>: registry.build02.ci.openshift.org/ci-op-2f4zdf4y/pipeline@sha256:f21d674b4027fefea63d6179870262ae2625ae96d220bd4b6f62a43ff70ffd67
```

**Comment by cynepco3hahue** [comment]
Ok now I remember, you should change all appearances of the `REPLACE_IMAGE` under 4.7 manifest to `quay.io/openshift-kni/performance-addon-operator:4.7-snapshot` https://github.com/openshift-kni/performance-addon-operators/blob/c9678684682b78df50125b2a5e52819a0bf29737/deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml#L188

**Comment by fromanirh** [comment]
> Ok now I remember, you should change all appearances of the `REPLACE_IMAGE` under 4.7 manifest to `quay.io/openshift-kni/performance-addon-operator:4.7-snapshot`
> 
> https://github.com/openshift-kni/performance-addon-operators/blob/c9678684682b78df50125b2a5e52819a0bf29737/deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml#L188

thanks for the tip, will update ASAP and repush.

**Pull request merged**
