### PR TITLE
Update owners aliases

### PR DESCRIPTION
**Pull request by fromanirh**
Remove inactive team members, and add new ones.

### CODE REVIEW

**Review by marcel-apf — APPROVED** [review]

**Comment by fromanirh** [comment]
/hold
Let's have a quorum before to change the OWNERS

**Comment by fromanirh** [comment]
Let's hear from @fedepaol @SchSeba @yanirq @MarSik @cynepco3hahue

**Review by MarSik — APPROVED** [review]

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp-operator-upgrade 
this PR doesn't change anything related to production code

**Comment by fromanirh** [comment]
/hold cancel
we have a quorum, thanks to all contributors and good luck to the new ones!

**Pull request merged**
