### PR TITLE
e2e: Reactivate stalld test

### PR DESCRIPTION
**Pull request by shajmakh**
Now that bugzillas 1912118 and 1903302 got resolved, we can remove the
skip from the stalld test again.

### CODE REVIEW

**Comment by fromanirh** [comment]
please don't push merge commits. Everything else lgtm.

**Comment by shajmakh** [comment]
I will fix this with new PR

**Comment by fromanirh** [comment]
> I will fix this with new PR

ok, but you could also just rebase + force push this one

**Pull request closed without merging**
