### PR TITLE
Update the metadata with 4.6 channel

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@fromanirh It generated the database with the wrong channel :(

**Review by fromanirh — APPROVED** [review]
/lgtm

**Comment by fromanirh** [comment]
/override e2e-gcp
this change cannot cause the test failures

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp
known kernel args issue + timeout + this patch cannot cause these failures - is not even exercised in these flows.

**Pull request merged**
