### PR TITLE
[release-4.8] Cherry picked from PR "e2e: Add stalld test and remove no longer needed skips #690" Bug 1985365: "re-activate stalld test and add new stalld priority test"

### PR DESCRIPTION
**Pull request by shajmakh**
Back-porting PR https://github.com/openshift-kni/performance-addon-operators/pull/690 to release-4.8 branch

### CODE REVIEW

**Comment by shajmakh** [comment]
> @shajmakh: This pull request references [Bugzilla bug 1905492](https://bugzilla.redhat.com/show_bug.cgi?id=1905492), which is invalid:
> 
> * expected the bug to be open, but it isn't
> * expected the bug to target the "4.8.0" release, but it targets "4.7.0" instead
> * expected the bug to be in one of the following states: NEW, ASSIGNED, ON_DEV, POST, POST, but it is CLOSED (ERRATA) instead
> * expected [Bugzilla bug 1905492](https://bugzilla.redhat.com/show_bug.cgi?id=1905492) to depend on a bug targeting a release in 4.9.0 and in one of the following states: MODIFIED, ON_QA, VERIFIED, but no dependents were found
> 
> Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.

@fromanirh @cynepco3hahue  the bug is already verified for 4.7/4.6 should I clone it with target release 4.8 and open it ? and btw shouldn't I also back-port these changes to 4.7 & 4.6?

**Comment by fromanirh** [comment]
> > @shajmakh: This pull request references [Bugzilla bug 1905492](https://bugzilla.redhat.com/show_bug.cgi?id=1905492), which is invalid:
> > 
> > * expected the bug to be open, but it isn't
> > * expected the bug to target the "4.8.0" release, but it targets "4.7.0" instead
> > * expected the bug to be in one of the following states: NEW, ASSIGNED, ON_DEV, POST, POST, but it is CLOSED (ERRATA) instead
> > * expected [Bugzilla bug 1905492](https://bugzilla.redhat.com/show_bug.cgi?id=1905492) to depend on a bug targeting a release in 4.9.0 and in one of the following states: MODIFIED, ON_QA, VERIFIED, but no dependents were found
> > 
> > Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.
> 
> @fromanirh @cynepco3hahue the bug is already verified for 4.7/4.6 should I clone it with target release 4.8 and open it ? and btw shouldn't I also back-port these changes to 4.7 & 4.6?

I think you need a new bug to backport the test fixes. The bug which it's referenced is about the production code changes, and indeed it's already solved and shipped.

**Comment by fromanirh** [comment]
/lgtm
/approve
actually let's see if the bot is happy in the current state. Being test fixes, I don't mind too much.

**Comment by fromanirh** [comment]
```
 Not mergeable. Should not have bugzilla/invalid-bug label. 
```
nope, need to fix BZ :)

**Comment by shajmakh** [comment]
> @shajmakh: This pull request references [Bugzilla bug 1985365](https://bugzilla.redhat.com/show_bug.cgi?id=1985365), which is invalid:
> 
> * expected dependent [Bugzilla bug 1905492](https://bugzilla.redhat.com/show_bug.cgi?id=1905492) to target a release in 4.9.0, but it targets "4.7.0" instead
> 
> Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.

seems like we do need to create a bug for 4.9 & from it to clone a bug for 4.8

**Comment by fromanirh** [comment]
> > @shajmakh: This pull request references [Bugzilla bug 1985365](https://bugzilla.redhat.com/show_bug.cgi?id=1985365), which is invalid:
> > 
> > * expected dependent [Bugzilla bug 1905492](https://bugzilla.redhat.com/show_bug.cgi?id=1905492) to target a release in 4.9.0, but it targets "4.7.0" instead
> > 
> > Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.
> 
> seems like we do need to create a bug for 4.9 & from it to clone a bug for 4.8

not sure, it's a very peculiar corner case the one you are handling now.
Do you need the explicit dependency in the bug?
image

**Comment by shajmakh** [comment]
> @shajmakh: This pull request references [Bugzilla bug 1985365](https://bugzilla.redhat.com/show_bug.cgi?id=1985365), which is invalid:
> 
> * expected the bug to target the "4.8.z" release, but it targets "4.9.0" instead
> * expected [Bugzilla bug 1985365](https://bugzilla.redhat.com/show_bug.cgi?id=1985365) to depend on a bug targeting a release in 4.9.0 and in one of the following states: VERIFIED, RELEASE_PENDING, CLOSED (ERRATA), CLOSED (CURRENTRELEASE), but no dependents were found
> 
> Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.

I think it indeed needs a dependent bug

**Pull request merged**
