### PR TITLE
Fixed KubeletConfig

### PR DESCRIPTION
**Pull request by slintes**
MCO has schema validation now and expects TyeMeta to be filled on embedded k8s KubeletConfiguration resource

### CODE REVIEW

**Comment by slintes** [comment]
/cherrypick release-4.4

don't merge before checking e2e
/hold

**Comment by cynepco3hahue** [comment]
@slintes So, in the end, all worked fine?

**Comment by slintes** [comment]
> @slintes So, in the end, all worked fine?

I epected something different (missing "metadata") but yes :slightly_smiling_face:

**Comment by cynepco3hahue** [comment]
Good for us :smile:

**Pull request merged**
