### PR TITLE
Advance ignition version

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Advance the ingnition version to be aligned with control-plane machine-configs
and avoid any problems with the deprecated version in the future.

### CODE REVIEW

**Comment by fromanirh** [comment]
could you please elaborate in the commit message why we need this and what the benefits are?

**Comment by cynepco3hahue** [comment]
> could you please elaborate in the commit message and/or PR cover letter ([#537 (comment)](https://github.com/openshift-kni/performance-addon-operators/pull/537#issue-568993251)) why we need this and what the benefits are?

Done

**Review by fromanirh — COMMENTED** [review]
/lgtm
/approve
it seems a trivial dep bump.

**Pull request merged**
