### PR TITLE
metadata: olm: rename operatorS -> operator in metadata

### PR DESCRIPTION
**Pull request by fromanirh**
We want to ship a single operator, and having a single container called
'*-operators-container' feels weird anyway. Furthermore, linting
tool complains about this naming

For consistency and to better represent the content, this
patch renames operator*s* to operator.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by slintes** [comment]
> I think we should fix names in the Makefile as well (see REGISTRY_IMAGE_NAME and OPERATOR_IMAGE_NAME)

and there are severl occurences in `openshift-ci/Dockerfile.registry.build` and `deploy/Dockerfile`as well

**Comment by fromanirh** [comment]
> I think we should fix names in the Makefile as well (see REGISTRY_IMAGE_NAME and OPERATOR_IMAGE_NAME)

NP, I can do that. We agree that in general this rename is a good thing, right?

**Comment by fromanirh** [comment]
also, even if it is slightly confusing, I believe the repo name _should_ be kept in the plural form (performance-addon-operator*S*)

**Comment by slintes** [comment]
> > I think we should fix names in the Makefile as well (see REGISTRY_IMAGE_NAME and OPERATOR_IMAGE_NAME)
> 
> NP, I can do that. We agree that in general this rename is a good thing, right?

yes :+1:

**Comment by slintes** [comment]
> also, even if it is slightly confusing, I believe the repo name _should_ be kept in the plural form (performance-addon-operator_S_)

it's weird indeed, and the chance that we get a 2nd operator in here is low IMHO, but yes, let's keep it

**Comment by fromanirh** [comment]
> https://github.com/openshift/release/blob/master/ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master.yaml
> 
> update prow as well, or e2e tests will fail.

ack. Problem is: should I change the prow config and get it merged before or after this patch?

**Comment by fromanirh** [comment]
> https://github.com/openshift/release/blob/master/ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master.yaml
> 
> update prow as well, or e2e tests will fail.

done: https://github.com/openshift/release/pull/6730

**Comment by davidvossel** [comment]
/test e2e-gcp

we've hit some sort of quota limit on gcp which is making tests fail. its not our code.

**Comment by fromanirh** [comment]
Looks like the error is still not from our code:
```
could not wait for build: the build bin failed after 3m52s with reason DockerBuildFailed: Docker build strategy has failed.

github.com/cri-o/cri-o@v1.9.0-beta.2.0.20191003162030-4775e1c05c26 requires
	github.com/containers/image/v5@v5.0.0 requires
	github.com/mtrmac/gpgme@v0.0.0-20170102180018-b2432428689c: invalid version: unknown revision b2432428689c
make: *** [Makefile:142: govet] Error 1
error: build error: running '/bin/bash -c set -o errexit; umask 0002; make build' failed with exit code 2
```

**Comment by davidvossel** [comment]
govet is failing during the build process... very strange 

```
Running gofmt
gofmt -s -l `find . -path ./vendor -prune -o -type f -name '*.go' -print`
Running go lint
hack/lint.sh
/go/bin/golint
Running go vet
go vet github.com/openshift-kni/performance-addon-operators/...
go: github.com/openshift/machine-config-operator@v4.2.0-alpha.0.0.20190917115525-033375cbe820+incompatible requires
	github.com/cri-o/cri-o@v1.9.0-beta.2.0.20191003162030-4775e1c05c26 requires
	github.com/containers/image/v5@v5.0.0 requires
	github.com/mtrmac/gpgme@v0.0.0-20170102180018-b2432428689c: invalid version: unknown revision b2432428689c
make: *** [Makefile:142: govet] Error 1
2020/01/20 13:35:01 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/01/20 13:35:02 Ran for 10m45s
2020/01/20 13:35:02 Submitted failure event to sentry (id=b152c076205f43fda8ddd4c0961aa206)
```

**Pull request merged**
