### PR TITLE
Use k8s cpuset package to convert CPUSet string to list

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by slintes** [comment]
nice :+1: 

/lgtm
/hold
feel free to remove hold when e2e looks good

can we close #108 in favour of this one?

**Comment by yanirq** [comment]
> can we close #108 in favour of this one?

#108 is a test fix , but it might be useful to use the functions here for the test if possible
/cc @dshchedr

**Comment by cynepco3hahue** [comment]
@yanirq it already done

**Comment by slintes** [comment]
test failures are unrelated, MCO drops KubeletConfigs atm.

/hold cancel
/override ci/prow/e2e-gcp
/cherrypick release-4.4

**Comment by slintes** [comment]
@cynepco3hahue can you please backport manually? I understand this is important enough, right?

**Comment by cynepco3hahue** [comment]
@slintes Sure will do

**Pull request merged**
