### PR TITLE
csv: add more metadata

### PR DESCRIPTION
**Pull request by fromanirh**
Add metadata to make the CSV look a bit nicer in the operatorHUB ui.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
/lgtm 
Assuming CI passes and REPLACE_IMAGE gets replaced in a proper manner

**Comment by fromanirh** [comment]
/hold
let's avoid premature merge

**Comment by fromanirh** [comment]
/hold
same reason as above

**Comment by fromanirh** [comment]
Probably @davidvossel whats to have a look to what I'm changing here.

**Comment by fromanirh** [comment]
uhm, this error
```
level=error msg="Error: Error reading DNS Record Set \"api.ci-op-cdcsmmn1-24cc7.origin-ci-int-gce.dev.openshift.com.\": googleapi: Error 503: Backend Error, backendError"
```
can hardly be caused by this patch

**Pull request merged**
