### PR TITLE
WIP: Add 0_config testsuit that is responsible for creating profile

### PR DESCRIPTION
**Pull request by dshchedr**
Changed default label from worker-rt to worker-cnf
Change default profile name from ci to performance

### CODE REVIEW

**Comment by slintes** [comment]
oh... I missed this... see #189

**Comment by dshchedr** [comment]
> oh... I missed this... see #189

yeah, your PR is more complete, let's close this one

**Comment by dshchedr** [comment]
Closed in favor of PR #189

**Pull request closed without merging**
