### PR TITLE
Point 4.5 CSVs to the 4.5-snapshot

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Review by fromanirh — COMMENTED** [review]
wait this is likely to break later in our pipeline.

**Comment by cynepco3hahue** [comment]
> wait this is likely to break later in our pipeline.

Can you please elaborate?

**Comment by fromanirh** [comment]
> > wait this is likely to break later in our pipeline.
> 
> Can you please elaborate?

nevermind, not really relevant anymore

**Review by fromanirh — APPROVED** [review]
/lgtm

**Pull request merged**
