### PR TITLE
dockerfile: add ping-helper image

### PR DESCRIPTION
**Pull request by fromanirh**
we want a dead-simple, minimal, trivial to maintain
image which we can use for connectivity tests
in our and openshift e2e tests.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by MarSik** [comment]
A good idea with an image like this is to make it so it supports this usage pattern:

oc run helper ping 8.8.8.8

Basically so arguments are directly executed in the shell.

**Comment by fromanirh** [comment]
> A good idea with an image like this is to make it so it supports this usage pattern:
> 
> podman run helper ping 8.8.8.8
> 
> Basically so arguments are directly executed in the shell.

good point! fixed and added usage example in the commit message

**Comment by marcel-apf** [comment]
@fromanirh what is the status of this PR? Do we need it?

**Comment by fromanirh** [comment]
not needed for now, we will re-evaluate later.

**Pull request closed without merging**
