### PR TITLE
update OWNERS 20220422

### PR DESCRIPTION
**Pull request by fromanirh**
Refresh the list of active contributors

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Review by jlojosnegros — APPROVED** [review]
/lgtm

**Review by marioferh — APPROVED** [review]
/lgtm

**Comment by fromanirh** [comment]
/override ci/prow/e2e-gcp
```
level=error msg=Cluster operator console Degraded is True with RouteHealth_Failed
```
this change cannot cause failures, especially infra failures

**Review by MarSik — APPROVED** [review]
/lgtm

**Pull request merged**
