### PR TITLE
version: bump to 4.7.2

### PR DESCRIPTION
**Pull request by fromanirh**
Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/test e2e-gcp-operator-upgrade
not sure is a flake/glitch

**Comment by fromanirh** [comment]
```
 error happened during read: read tcp 10.130.14.188:39228->172.217.193.128:443: read: connection reset by peer
```

**Review by MarSik — APPROVED** [review]
It looks ok, but it is a lot of text..

**Pull request merged**
