### PR TITLE
hack: Run PPC tests as part of the functional tests

### PR DESCRIPTION
**Pull request by marcel-apf**
Use the same CI lane to test PPC regression.

Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>

### CODE REVIEW

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by marcel-apf** [comment]
Needs also a change in the openshift CI

**Comment by swatisehgal** [comment]
We would have to make sure `create-performance-profile` target is executed before `functests-only` target to prevent functional tests from failing in case PPC binary does not exist. Please refer to the PR here: https://github.com/openshift-kni/performance-addon-operators/pull/615.

**Comment by marcel-apf** [comment]
Retired, not longer needed because of: https://github.com/openshift/release/pull/17818

**Pull request closed without merging**
