### PR TITLE
Add performance-profile-creator binary to the PAO Dockerfile

### PR DESCRIPTION
**Pull request by swatisehgal**
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

### CODE REVIEW

**Comment by swatisehgal** [comment]
/hold 
Hold till both https://github.com/openshift-kni/performance-addon-operators/pull/513 and https://github.com/openshift/release/pull/15332 are merged.

**Comment by fromanirh** [comment]
/hold cancel
both related PRs merged.

**Comment by fromanirh** [comment]
```
level=error
level=error msg=Error: Request "Create IAM Members roles/compute.viewer serviceAccount:ci-op-whlkwl93-2a172-g8nt2-w@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" returned error: Error applying IAM policy for project "openshift-gce-devel-ci": Error setting IAM policy for project "openshift-gce-devel-ci": googleapi: Error 400: Deleted member 'ci-op-fzl02i-openshift-i-kbrhb@openshift-gce-devel-ci.iam.gserviceaccount.com?uid=110366228005756524537' is not deleted., badRequest
level=error
level=error msg=  on ../tmp/openshift-install-842980306/iam/main.tf line 6, in resource "google_project_iam_member" "worker-compute-viewer":
level=error msg=   6: resource "google_project_iam_member" "worker-compute-viewer" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 
```
the `openshift/release` fix helped. We passed the point on which we previously failed. Now we need to cope with the CI failures due to high load.

**Pull request merged**
