### PR TITLE
[release-4.4] Add additional kerenel arguments option in CRD

### PR DESCRIPTION
**Pull request by yanirq**
Manual cherry pick of #133

### CODE REVIEW

**Comment by fromanirh** [comment]
why did the automated cherry-pick fail?
looks ok to me, nothing surprising here.

**Comment by yanirq** [comment]
> why did the automated cherry-pick fail?
> looks ok to me, nothing surprising here.

@fromanirh Failed on auto merge because NUMA field does not exist in 4.4

**Pull request merged**
