### PR TITLE
e2e: add workload hints test

### PR DESCRIPTION
**Pull request by cynepco3hahue**
The test verifies kernel arguments and tuned profile after enabling the power saving and disabling the real-time.

### CODE REVIEW

**Comment by yanirq** [comment]
This PR will now have to be implemented under https://github.com/openshift/cluster-node-tuning-operator  since PAO code base has moved to NTO

**Comment by cynepco3hahue** [comment]
close in favor of https://github.com/openshift/cluster-node-tuning-operator/pull/339

**Pull request closed without merging**
