### PR TITLE
Add Polarion reporter

### PR DESCRIPTION
**Pull request by dshchedr**
This tool allows us to export results of testing to polarion.

For example, running this command will start tests and create polarion_results.xml file that can be imported to polarion:
GOFLAGS=-mod=vendor ginkgo functests -- -ginkgo.skip "Updating parameters in performance profile" -polarion-custom-plannedin=OCP-4_4 -polarion-execution=true -polarion-project-id=OSE -polarion-report-file=/tmp/polarion_results.xml

### CODE REVIEW

**Comment by dshchedr** [comment]
:-\ looks like I accidentally closed this PR, will recreate new one

**Comment by yuvalk** [comment]
> :-\ looks like I accidentally closed this PR, will recreate new one

I think you can
/reopen
it

**Comment by dshchedr** [comment]
> > :-\ looks like I accidentally closed this PR, will recreate new one
> 
> I think you can
> /reopen
> it

Yeah, you are right.. 
but I already created new PR :(

**Comment by yuvalk** [comment]
for the future...

**Pull request closed without merging**
