### PR TITLE
Generate CSV 4.7 and move all variable from 4.6 to 4.7

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by marcel-apf** [comment]
Looks good to me, I'll let @fromanirh to go over it himself, maybe I missed anything.

**Review by fromanirh — APPROVED** [review]
/lgtm

**Comment by fromanirh** [comment]
Are we sure the OCP infra is reasy for 4.7 yet?
```
 hack/run-upgrade-tests.sh
Operator exists, verifying the version
Channel 4.5 is not equal to 4.6, exit 
```

**Pull request merged**
