### PR TITLE
[release-4.10] OCPBUGS-4165: Add ktimer to PAO tuned profile

### PR DESCRIPTION
**Pull request by jlojosnegros**
Backport of openshift/cluster-node-tuning-operator#510

### CODE REVIEW

**Comment by fromanirh** [comment]
do we have dependencies on tuned/rhcos components possibly not available on 4.10?

**Comment by jlojosnegros** [comment]
> do we have dependencies on tuned/rhcos components possibly not available on 4.10?

We depend on the corresponding patch applied to the kernel but the ticket for that is closed so I think we are ok on that side.

**Review by MarSik — APPROVED** [review]
/lgtm

**Pull request merged**
