### PR TITLE
e2e: fix runtime class test failures

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Fix runtime class test failures when it runs on the environment with more than one worker-cnf node.

- add proper node selector to the pod
- revert `Eventually` that I added before because thought it was some race
the condition between the start of the container and the update of the cgroup

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Review by fromanirh — COMMENTED** [review]
I would have preferred a separate revert + explicit fix
so I'll let the other reviewers decide

**Comment by yanirq** [comment]
> I would have preferred a separate revert + explicit fix
> so I'll let the other reviewers decide

The description in the PR might be confusing so maybe indeed that's the way to go

**Comment by cynepco3hahue** [comment]
@fromanirh Do you want it under the separate PR or commit?

**Comment by cynepco3hahue** [comment]
@fromanirh @yanirq Updated the PR

**Review by fromanirh — APPROVED** [review]
/lgtm

**Comment by fromanirh** [comment]
/hold
let's wait few hours until we reach consensus about https://github.com/openshift-kni/performance-addon-operators/pull/355
this is just about serializing changes and minimizing disruption, this PR is completely fine.

**Pull request merged**
